apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  lambda-url: aHR0cHM6Ly95b3VyLWxhbWJkYS11cmwuYW1hem9uYXdzLmNvbS9wcm9kL3lvdXItZW5kcG9pbnQ= # base64 encoded value of "https://your-lambda-url.amazonaws.com/prod/your-endpoint"
  aws-region: dXMtV2VzdC0y # base64 encoded value of "us-west-2"